{
  parserClass="ru.compscicenter.jetbrains.octave.parser.OctaveParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Octave"
  psiImplClassSuffix="Impl"
  psiPackage="ru.compscicenter.jetbrains.octave.psi"
  psiImplPackage="ru.compscicenter.jetbrains.octave.psi.impl"

  elementTypeHolderClass="ru.compscicenter.jetbrains.octave.psi.OctaveTypes"
  elementTypeClass="ru.compscicenter.jetbrains.octave.psi.OctaveElementType"
  tokenTypeClass="ru.compscicenter.jetbrains.octave.psi.OctaveTokenType"

  psiImplUtilClass="ru.compscicenter.jetbrains.octave.psi.impl.OctavePsiImplUtil"
}

octaveFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {mixin="ru.compscicenter.jetbrains.octave.psi.impl.OctaveNamedElementImpl"
  implements="ru.compscicenter.jetbrains.octave.psi.OctaveNamedElement" methods=[getKey getValue getName setName getNameIdentifier getPresentation]}